sonar.projectKey=loyertracker-frontend
sonar.projectName=LoyerTracker – Frontend

sonar.sources=src
sonar.exclusions=**/*.spec.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/loyertracker/lcov.info

sonar.qualitygate.wait=true
